# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: "ubuntu-22.04"
  tools: 
    python: "3.8"
  commands:
    - pip install poetry pdoc
    - poetry config virtualenvs.create false
    - poetry install --extras "sil analysis"
    - pdoc --docformat google --template-dir docs/custom/ -o docs/output/ vessim/ examples/cosim_example.py examples/sil_example.py docs/extra/About\ Vessim.py docs/extra/Concept.py docs/extra/Getting\ Started docs/extra/Installation.py
    - mkdir --parents $READTHEDOCS_OUTPUT/html/
    - cp --recursive docs/output/* $READTHEDOCS_OUTPUT/html/