# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

formats: all

python:
  version: 3.8
  install:
    - requirements: site/requirements.txt

build:
  image: latest

mkdocs:
  configuration: null
  fail_on_warning: false