version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  jobs:
    post_create_environment:
      - pip install poetry
    post_install:
      - poetry install --extras "sil docs"

sphinx:
  configuration: docs/conf.py