name: Build

# event that triggers workflow
# runs on every pull request
on: 
  pull_request:
    branches:
      - pipeline_adjustments #main

jobs:
  integration-tests:
    # specifies the os that the job will run on 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.12]
    steps:
    # downloads the repository code to the runner's file system for workflow access
    - uses: actions/checkout@v4
      with:
        ref: 'pipeline_adjustments'

    # installs poetry without automatic creation of a virtual environment
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false

    # sets up python environment with specified versions 
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'    

    - name: Build package out of local poject
      run: poetry build

    - name: Install package 
      run: pip install dist/*.tar.gz 

    - name: Run example scenario and compare result
      run: |
        python examples/basic_example.py --out result.csv
        if diff result.csv examples/data/base_result.csv; then
          echo "Files are identical"
        else
          echo "Differences found between the resulting data and the data from the repository."
          exit 1
        fi