name: Build

# event that triggers workflow
# runs on every pull request
on: 
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    # specifies the os that the job will run on 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.12]
    steps:
    # downloads the repository code to the runner's file system for workflow access
    - uses: actions/checkout@v4

    # sets up python environment with specified versions 
    - name: Set up python ${{ matrix.python-version }}
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # installs poetry and configures it
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    # loads cached venv if it exists
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    # install dependencies if cache not available
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root --extras "sil dev"

    # install library 
    - name: Install root project
      run: poetry install --no-interaction --extras "sil dev"

    # build package
    - name: Build package out of local poject
      run: poetry build

    - name: Install package 
      run: pip install dist/*.tar.gz 

    #- name: Run example scenario and compare result
    #  run: |
     #   python examples/basic_example.py --out result.csv
     #   if diff result.csv examples/data/base_result.csv; then
     #     echo "Files are identical"
     #   else
     #     echo "Differences found between the resulting data and the data from the repository."
    #      exit 1
    #    fi