name: Documentation

# event that triggers workflow
# runs on every push
on: 
  push:

jobs:
  documentation:
     # specifies the os that the job will run on 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.11]
    steps:
    # downloads the repository code to the runner's file system for workflow access
    - uses: actions/checkout@v2
      
    # sets up python environment with specified versions 
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}   
    
    # installs poetry without automatic creation of a virtual environment
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false
    
    - name: Install dependencies
      run: |
        poetry install --extras "sil analysis"
        mkdir docs
        poetry export -f requirements.txt --output docs/requirements.txt

    - name: Generate Documentation
      run: |
        pdoc --html --force -o docs/ vessim
        
    - name: Update branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout documentation_tests
        git add .
        git commit -m "Update documentation" || echo "No changes to commit"
        git push -f origin documentation_tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}