name: linting-and-type-checking

# event that triggers workflow
# runs on every commit
on: 
  push:

jobs:
  linting-and-type-checking:
    # specifies the os that the job will run on 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.11]
    steps:
    # downloads the repository code to the runner's file system for workflow access
    - uses: actions/checkout@v2
    - uses: chartboost/ruff-action@v1
       
    # sets up python environment with specified versions 
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}   
    
    # installs poetry without automatic creation of a virtual environment
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false
     
    - name: Install dependencies
      run: poetry install

    - name: Run type checker
      run: mypy vessim

    - name: Run linter
      run: ruff .